/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author 19522
 */
public class SaleManagement extends javax.swing.JFrame {

    /**
     * Creates new form SaleManagement
     */
    public SaleManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BackBtn = new javax.swing.JLabel();
        ParentPanel = new javax.swing.JTabbedPane();
        SearchTab = new javax.swing.JPanel();
        SearchBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        EditChangeBtn = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        EditChangeBtn1 = new javax.swing.JButton();
        SearchTxb6 = new javax.swing.JTextField();
        AuthorCb = new javax.swing.JComboBox<>();
        TypeCb = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        SearchTxb7 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        SearchTable = new javax.swing.JTable();
        CreateBillTab = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        SearchTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        DeleteBtn1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        DeleteBtn2 = new javax.swing.JButton();
        DeleteBtn3 = new javax.swing.JButton();
        PurchasedBillTab = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        SearchTable2 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        SearchTable3 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        DeleteBtn4 = new javax.swing.JButton();
        DeleteBtn5 = new javax.swing.JButton();
        SearchTxb8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TypeCb1 = new javax.swing.JComboBox<>();
        SearchBtn1 = new javax.swing.JButton();
        ReturnTab = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ViewTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 153, 200));

        jLabel1.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SALE&BILL MANAGEMENT");

        BackBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Component/icons8_previous_70px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackBtn)
                .addGap(373, 373, 373)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BackBtn))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        ParentPanel.setBackground(new java.awt.Color(204, 204, 255));

        SearchTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SearchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Component/Minisize/icons8_search_35px.png"))); // NOI18N
        SearchBtn.setToolTipText("Search");
        SearchTab.add(SearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 240, -1, 52));

        DeleteBtn.setBackground(new java.awt.Color(255, 51, 102));
        DeleteBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DeleteBtn.setText("+");
        SearchTab.add(DeleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 440, 60, 51));

        EditChangeBtn.setBackground(new java.awt.Color(255, 204, 204));
        EditChangeBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EditChangeBtn.setText("-");
        EditChangeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditChangeBtnMouseClicked(evt);
            }
        });
        SearchTab.add(EditChangeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 440, 60, 51));

        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("All");
        SearchTab.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(945, 9, -1, -1));

        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRadioButton2.setText("Filter");
        jRadioButton2.setToolTipText("");
        SearchTab.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1216, 9, -1, -1));

        EditChangeBtn1.setBackground(new java.awt.Color(153, 255, 153));
        EditChangeBtn1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EditChangeBtn1.setText("SELECT");
        EditChangeBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditChangeBtn1MouseClicked(evt);
            }
        });
        SearchTab.add(EditChangeBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 530, 116, 51));

        SearchTxb6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SearchTxb6.setText("Num");
        SearchTxb6.setToolTipText("Search Here....");
        SearchTab.add(SearchTxb6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 440, 70, 50));

        AuthorCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SearchTab.add(AuthorCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(1055, 179, 182, 45));

        TypeCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SearchTab.add(TypeCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(1055, 116, 182, 45));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Type");
        SearchTab.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(964, 127, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Author");
        SearchTab.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(964, 190, -1, -1));

        SearchTxb7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SearchTxb7.setText("Search name ...");
        SearchTxb7.setToolTipText("Search Here....");
        SearchTab.add(SearchTxb7, new org.netbeans.lib.awtextra.AbsoluteConstraints(942, 56, 321, 42));

        jScrollPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        SearchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Author", "Type", "Amout", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        SearchTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        SearchTable.setCellSelectionEnabled(true);
        SearchTable.setGridColor(new java.awt.Color(0, 0, 0));
        SearchTable.setShowGrid(true);
        jScrollPane1.setViewportView(SearchTable);

        SearchTab.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 590));

        ParentPanel.addTab("Choose Book", new javax.swing.ImageIcon(getClass().getResource("/GUI/Component/Minisize/icons8_search_35px.png")), SearchTab); // NOI18N

        CreateBillTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        SearchTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Author", "Type", "Amout", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        SearchTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        SearchTable1.setCellSelectionEnabled(true);
        SearchTable1.setGridColor(new java.awt.Color(0, 0, 0));
        SearchTable1.setShowGrid(true);
        jScrollPane3.setViewportView(SearchTable1);

        CreateBillTab.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 930, 280));

        jLabel2.setText("Bill ID");
        CreateBillTab.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, -1));

        jTextField1.setText("jTextField1");
        CreateBillTab.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 160, 30));

        jLabel3.setText("Date");
        CreateBillTab.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 60, -1, -1));
        CreateBillTab.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 50, 210, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CreateBillTab.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, 180, 30));

        jLabel4.setText("Customer ID");
        CreateBillTab.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, -1, -1));

        DeleteBtn1.setBackground(new java.awt.Color(255, 51, 102));
        DeleteBtn1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DeleteBtn1.setText("CANCEL");
        CreateBillTab.add(DeleteBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 510, 116, 51));

        jTextField2.setText("jTextField1");
        CreateBillTab.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, 210, 50));

        jLabel5.setText("Total");
        CreateBillTab.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, 30, 30));

        jLabel8.setText("Receive");
        CreateBillTab.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 430, 50, 30));

        jTextField3.setText("jTextField1");
        CreateBillTab.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 420, 210, 50));

        DeleteBtn2.setBackground(new java.awt.Color(255, 51, 102));
        DeleteBtn2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DeleteBtn2.setText("DELETE");
        CreateBillTab.add(DeleteBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 360, 116, 51));

        DeleteBtn3.setBackground(new java.awt.Color(255, 51, 102));
        DeleteBtn3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DeleteBtn3.setText("CONFIRM");
        CreateBillTab.add(DeleteBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 510, 116, 51));

        ParentPanel.addTab("Create Bill", CreateBillTab);

        PurchasedBillTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        SearchTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Author", "Type", "Amout", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        SearchTable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        SearchTable2.setCellSelectionEnabled(true);
        SearchTable2.setGridColor(new java.awt.Color(0, 0, 0));
        SearchTable2.setShowGrid(true);
        jScrollPane4.setViewportView(SearchTable2);

        PurchasedBillTab.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 930, 260));

        jScrollPane5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        SearchTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Author", "Type", "Amout", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        SearchTable3.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        SearchTable3.setCellSelectionEnabled(true);
        SearchTable3.setGridColor(new java.awt.Color(0, 0, 0));
        SearchTable3.setShowGrid(true);
        jScrollPane5.setViewportView(SearchTable3);

        PurchasedBillTab.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 280));

        jLabel9.setText("Detail");
        PurchasedBillTab.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, -1, -1));

        DeleteBtn4.setBackground(new java.awt.Color(255, 51, 102));
        DeleteBtn4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DeleteBtn4.setText("RETURN");
        PurchasedBillTab.add(DeleteBtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 400, 116, 51));

        DeleteBtn5.setBackground(new java.awt.Color(255, 51, 102));
        DeleteBtn5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DeleteBtn5.setText("CANCEL");
        PurchasedBillTab.add(DeleteBtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 510, 116, 51));

        SearchTxb8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SearchTxb8.setText("Search name ...");
        SearchTxb8.setToolTipText("Search Here....");
        PurchasedBillTab.add(SearchTxb8, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 20, 321, 42));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Customer ID");
        PurchasedBillTab.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 90, -1, -1));

        TypeCb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        PurchasedBillTab.add(TypeCb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 80, 182, 45));

        SearchBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Component/Minisize/icons8_search_35px.png"))); // NOI18N
        SearchBtn1.setToolTipText("Search");
        PurchasedBillTab.add(SearchBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 150, -1, 52));

        ParentPanel.addTab("Purchased Bills", new javax.swing.ImageIcon(getClass().getResource("/GUI/Component/Minisize/icons8_Plus_+_35px.png")), PurchasedBillTab); // NOI18N

        jScrollPane2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ViewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Address", "PhoneNumber", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ViewTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        ViewTable.setCellSelectionEnabled(true);
        ViewTable.setGridColor(new java.awt.Color(0, 0, 0));
        ViewTable.setShowGrid(true);
        jScrollPane2.setViewportView(ViewTable);

        javax.swing.GroupLayout ReturnTabLayout = new javax.swing.GroupLayout(ReturnTab);
        ReturnTab.setLayout(ReturnTabLayout);
        ReturnTabLayout.setHorizontalGroup(
            ReturnTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReturnTabLayout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(194, Short.MAX_VALUE))
        );
        ReturnTabLayout.setVerticalGroup(
            ReturnTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );

        ParentPanel.addTab("Return Bills", new javax.swing.ImageIcon(getClass().getResource("/GUI/Component/Minisize/icons8_eye_35px.png")), ReturnTab); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ParentPanel)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ParentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditChangeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditChangeBtnMouseClicked
        ParentPanel.setSelectedIndex(2);
    }//GEN-LAST:event_EditChangeBtnMouseClicked

    private void EditChangeBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditChangeBtn1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_EditChangeBtn1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaleManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaleManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaleManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaleManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SaleManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AuthorCb;
    private javax.swing.JLabel BackBtn;
    private javax.swing.JPanel CreateBillTab;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JButton DeleteBtn1;
    private javax.swing.JButton DeleteBtn2;
    private javax.swing.JButton DeleteBtn3;
    private javax.swing.JButton DeleteBtn4;
    private javax.swing.JButton DeleteBtn5;
    private javax.swing.JButton EditChangeBtn;
    private javax.swing.JButton EditChangeBtn1;
    private javax.swing.JTabbedPane ParentPanel;
    private javax.swing.JPanel PurchasedBillTab;
    private javax.swing.JPanel ReturnTab;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JButton SearchBtn1;
    private javax.swing.JPanel SearchTab;
    private javax.swing.JTable SearchTable;
    private javax.swing.JTable SearchTable1;
    private javax.swing.JTable SearchTable2;
    private javax.swing.JTable SearchTable3;
    private javax.swing.JTextField SearchTxb6;
    private javax.swing.JTextField SearchTxb7;
    private javax.swing.JTextField SearchTxb8;
    private javax.swing.JComboBox<String> TypeCb;
    private javax.swing.JComboBox<String> TypeCb1;
    private javax.swing.JTable ViewTable;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
